<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select City</name>
   <tag></tag>
   <elementGuidId>173401f7-ef64-47ea-bb7c-0b9481d275c3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlCity</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value.bind</name>
      <type>Main</type>
      <value>orderCustController.order.city &amp; validateOnBlur</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled.bind</name>
      <type>Main</type>
      <value>orderCustController.isReadOnly</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>au-target form-control placeholder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>au-target-id</name>
      <type>Main</type>
      <value>844</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Select City
              Acqui TermeAlbera LigureAlessandriaAlfiano NattaAlice Bel ColleAlluvioni Cambio'Altavilla MonferratoAlzano ScriviaArquata ScriviaAvolascaBalzolaBasaluzzoBassignanaBelforte MonferratoBergamascoBerzano di TortonaBistagnoBorghetto di BorberaBorgo San MartinoBorgoratto AlessandrinoBosco MarengoBosioBozzoleBrignano FrascataBrignano-FrascataCabella LigureCamagna MonferratoCaminoCantalupo LigureCapriata d'OrbaCarbonara ScriviaCarentinoCarezzanoCarpenetoCarrega LigureCarrosioCartosioCasal CermelliCasale MonferratoCasaleggio BoiroCasalnocetoCasascoCassano SpinolaCassineCassinelleCastellaniaCastellar GuidobonoCastellazzo BormidaCastelletto d'ErroCastelletto d'OrbaCastelletto MerliCastelletto MonferratoCastelnuovo BormidaCastelnuovo ScriviaCastelspinaCavatoreCella MonteCeresetoCerreto GrueCerrina MonferratoConioloConzanoCosta VescovatoCremolinoCuccaro MonferratoDeniceDerniceFabbrica CuroneFelizzanoFraconaltoFrancavilla BisioFrascaroFrassinello MonferratoFrassineto PoFresonaraFrugaroloFubineFubine MonferratoGabianoGamaleroGarbagnaGavazzanaGaviGiaroleGremiascoGrognardoGrondonaGuazzoraIsola Sant'AntonioLermaLuMalvicinoMasioMelazzoMERANAMirabello MonferratoMolareMolino dei TortiMombello MonferratoMomperoneMoncestinoMongiardino LigureMonlealeMontacutoMontaldeoMontaldo BormidaMontecastelloMontechiaro d'AcquiMontegiocoMontemarzinoMorano sul PoMorbelloMorneseMorsascoMurisengoNovi LigureOccimianoOdalengo GrandeOdalengo PiccoloOlivolaOrsara BormidaOttiglioOvadaOviglioOzzano MonferratoPadernaParetoParodi LigurePasturanaPecetto di ValenzaPietra MarazziPioveraPomaro MonferratoPontecuronePontesturaPontiPonzano MonferratoPonzonePozzol GroppoPozzolo FormigaroPrascoPredosaQuargnentoQuattordioRicaldoneRivalta BormidaRivaroneRocca GrimaldaRoccaforte LigureRocchetta LigureRosignano MonferratoSala MonferratoSaleSan CristoforoSan Giorgio MonferratoSan Salvatore MonferratoSan Sebastiano CuroneSant'Agata FossiliSardiglianoSarezzanoSerralunga di CreaSerravalle ScriviaSezzadioSilvano d'OrbaSoleroSolonghelloSpigno MonferratoSpineto ScriviaStazzanoStreviTagliolo MonferratoTassaroloTerruggiaTerzoTicinetoTortonaTrevilleTrisobbioValenzaValmaccaVignale MonferratoVignole BorberaViguzzoloVilladeatiVillalverniaVillamiroglioVillanova MonferratoVillaromagnanoVisoneVolpedoVolpeglinoVoltaggio
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlCity&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='ddlCity']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='divCity']/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
