<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Level1Energy</name>
   <tag></tag>
   <elementGuidId>2bd3f489-d5cb-4523-8d4f-e98a64f26d60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ej-grid[@id='gvSummaryGrid']//div//div[@class='e-headercelldiv'][contains(text(),'Level')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
