<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(MMDDYYYY)</name>
   <tag></tag>
   <elementGuidId>0d0f3fc1-5448-455d-87a7-55d64c019329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = '
                (MM/DD/YYYY)
              ' or . = '
                (MM/DD/YYYY)
              ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lblBirthDate']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                (MM/DD/YYYY)
              </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lblBirthDate&quot;)/span[2]</value>
   </webElementProperties>
</WebElementEntity>
