<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_icon-eye</name>
   <tag></tag>
   <elementGuidId>2493956a-07ff-46fc-9d41-cb481087dc68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gvAssociates&quot;)/div[@class=&quot;e-gridcontent&quot;]/div[1]/table[@class=&quot;e-table&quot;]/tbody[1]/tr[@class=&quot;e-row e-hover&quot;]/td[@class=&quot;e-rowcell e-templatecell&quot;]/div[@class=&quot;aurtmpl13448f8f-797d-4529-bab5-b3ef9949998e ej-aurelia-template&quot;]/button[@class=&quot;btn btn-edit au-target&quot;]/span[@class=&quot;icon-eye&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[6]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-eye</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssociates&quot;)/div[@class=&quot;e-gridcontent&quot;]/div[1]/table[@class=&quot;e-table&quot;]/tbody[1]/tr[@class=&quot;e-row e-hover&quot;]/td[@class=&quot;e-rowcell e-templatecell&quot;]/div[@class=&quot;aurtmpl13448f8f-797d-4529-bab5-b3ef9949998e ej-aurelia-template&quot;]/button[@class=&quot;btn btn-edit au-target&quot;]/span[@class=&quot;icon-eye&quot;]</value>
   </webElementProperties>
</WebElementEntity>
